# Generated by Django 3.1 on 2020-10-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default='2020-10-19 14:45:58.084083'),
            preserve_default=False,
        ),
    ]
