# Generated by Django 3.1 on 2020-10-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default='India', max_length=50),
            preserve_default=False,
        ),
    ]
