# Generated by Django 3.1 on 2020-10-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='topic1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='topic2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='topic3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='topic4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='topic5',
        ),
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
