# Generated by Django 3.1 on 2020-11-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201020_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='user2',
            field=models.IntegerField(),
        ),
    ]
