# Generated by Django 3.1 on 2020-11-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201102_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user2', models.IntegerField()),
                ('accepted', models.BooleanField()),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
