# Generated by Django 3.1 on 2020-11-03 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_friend2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend2',
        ),
    ]
